import Navbar from "@/components/NavBar";
import ToastContainer from "@/components/ToastContainer";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="h-screen flex flex-col">
				<Navbar />
				<div className="container mx-auto flex flex-grow px-4">{children}</div>
				<ToastContainer />
			</body>
		</html>
	);
}
