# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name":"Google",
    "symbol":"GOOGL",
    "price":100
}


###
# @name createWallet
POST http://localhost:3000/wallets
Content-Type: application/json

###
# @name createWalletAsset
@walletId = {{createWallet.response.body._id}}
@assetId = {{createAsset.response.body._id}}
POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId":"{{assetId}}",
    "shares":10
}

###
# @name createOrder
POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId":"{{walletId}}",
    "assetId":"{{assetId}}",
    "shares":5,
    "type":"BUY",
    "price":100,
    "partial": 10
}

###
# @name getOrders
GET http://localhost:3000/orders?walletId={{walletId}}

###
# @name getWallets
GET http://localhost:3000/wallets/{{walletId}}