# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name":"Google",
    "symbol":"GOOGL",
    "price":100
}

###
# @name getAssets
GET http://localhost:3000/assets

###
# @name getAsset
@assetSymbol = {{createAsset.response.body.symbol}}
GET http://localhost:3000/assets/{{assetSymbol}}